// Code generated by gone; DO NOT EDIT.
package main

import (
	"github.com/gone-io/gone"
)

func Priest(cemetery gone.Cemetery) error {
	cemetery.Bury(NewAdder())
	cemetery.Bury(NewComputer())
	return nil
}
