// Code generated by goneCtr. DO NOT EDIT.

package gin

import (
	"github.com/gone-io/gone"
	gomock "go.uber.org/mock/gomock"
)

func MockPriest(cemetery gone.Loader, ctrl *gomock.Controller) {
	cemetery.Load(NewMockController(ctrl))
	cemetery.Load(NewMockHandleProxyToGin(ctrl))
	cemetery.Load(NewMockXContext(ctrl))
	cemetery.Load(NewMockResponser(ctrl))
	cemetery.Load(NewMockHttInjector(ctrl))
	cemetery.Load(NewMockMiddleware(ctrl))
}
