package main

import (
	"github.com/gone-io/gone/tools/gone/app"
	"github.com/gone-io/gone/tools/gone/mock"
	"github.com/gone-io/gone/tools/gone/priest"
	"github.com/urfave/cli/v2"
	"log"
	"os"
)

func createPriestCommand() *cli.Command {
	var flags = []cli.Flag{
		&cli.StringSliceFlag{
			Name:     "s",
			Usage:    "scan package dir",
			Required: true,
		},

		&cli.StringFlag{
			Name:     "p",
			Value:    "",
			Usage:    "package name",
			Required: true,
		},

		&cli.StringFlag{
			Name:     "f",
			Value:    "",
			Usage:    "function name",
			Required: true,
		},

		&cli.StringFlag{
			Name:     "o",
			Value:    "",
			Usage:    "output filepath",
			Required: true,
		},

		&cli.BoolFlag{
			Name:  "stat",
			Value: false,
			Usage: "stat process time",
		},
		&cli.BoolFlag{
			Name:  "w",
			Value: false,
			Usage: "watch files change",
		},
	}

	return &cli.Command{
		Name:        "priest",
		Usage:       "-s ${scanPackageDir} -p ${pkgName} -f ${funcName} -o ${outputFilePath} [-w]",
		Description: "generate gone priest function",
		Flags:       flags,
		Action:      priest.Action,
	}
}

func createMockCommand() *cli.Command {
	return &cli.Command{
		Name:        "mock",
		Usage:       "-f ${fromGoFile} -o ${outGoFile}",
		Description: "patch code which is generated by github.com/golang/mock/mockgen, add `gone.flag` to MockStructure",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "f",
				Usage: "FromGoFile",
			},
			&cli.StringFlag{
				Name:     "o",
				Usage:    "outGoFile",
				Required: true,
			},
		},
		Action: mock.Action,
	}
}

func createAppCommand() *cli.Command {
	var flags = []cli.Flag{
		&cli.StringFlag{
			Name:    "template",
			Aliases: []string{"t"},
			Value:   "web",
			Usage:   "template: only support web、web+mysql, more will be supported in the future",
		},

		&cli.StringFlag{
			Name:    "mod",
			Aliases: []string{"m"},
			Usage:   "modName",
		},
	}

	return &cli.Command{
		Name:        "create",
		Usage:       "[-t ${template} [-m ${modName}]] ${appName}",
		Description: "create a gone app",
		Flags:       flags,
		Action:      app.Action,
	}
}

func create() *cli.App {
	return &cli.App{
		Name:           "gone",
		Description:    "generate gone code or generate gone app",
		DefaultCommand: "priest",
		Commands: []*cli.Command{
			createPriestCommand(),
			createMockCommand(),
			createAppCommand(),
		},
	}
}

func run(args ...string) int {
	tool := create()
	err := tool.Run(args)
	if err != nil {
		log.Println(err.Error())
		return 1
	}
	return 0
}

func main() {
	code := run(os.Args...)
	os.Exit(code)
}
