// Code generated by MockGen. DO NOT EDIT.
// Source: xorm.io/xorm (interfaces: EngineInterface)
//
// Generated by this command:
//
//	mockgen -package xorm -destination=./engine_mock_test.go xorm.io/xorm EngineInterface
//

// Package xorm is a generated GoMock package.
package xorm

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	xorm "xorm.io/xorm"
	caches "xorm.io/xorm/caches"
	contexts "xorm.io/xorm/contexts"
	dialects "xorm.io/xorm/dialects"
	log "xorm.io/xorm/log"
	names "xorm.io/xorm/names"
	schemas "xorm.io/xorm/schemas"
)

// MockEngineInterface is a mock of EngineInterface interface.
type MockEngineInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEngineInterfaceMockRecorder
	isgomock struct{}
}

// MockEngineInterfaceMockRecorder is the mock recorder for MockEngineInterface.
type MockEngineInterfaceMockRecorder struct {
	mock *MockEngineInterface
}

// NewMockEngineInterface creates a new mock instance.
func NewMockEngineInterface(ctrl *gomock.Controller) *MockEngineInterface {
	mock := &MockEngineInterface{ctrl: ctrl}
	mock.recorder = &MockEngineInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngineInterface) EXPECT() *MockEngineInterfaceMockRecorder {
	return m.recorder
}

// AddHook mocks base method.
func (m *MockEngineInterface) AddHook(hook contexts.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHook", hook)
}

// AddHook indicates an expected call of AddHook.
func (mr *MockEngineInterfaceMockRecorder) AddHook(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHook", reflect.TypeOf((*MockEngineInterface)(nil).AddHook), hook)
}

// Alias mocks base method.
func (m *MockEngineInterface) Alias(alias string) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alias", alias)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Alias indicates an expected call of Alias.
func (mr *MockEngineInterfaceMockRecorder) Alias(alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alias", reflect.TypeOf((*MockEngineInterface)(nil).Alias), alias)
}

// AllCols mocks base method.
func (m *MockEngineInterface) AllCols() *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllCols")
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// AllCols indicates an expected call of AllCols.
func (mr *MockEngineInterfaceMockRecorder) AllCols() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllCols", reflect.TypeOf((*MockEngineInterface)(nil).AllCols))
}

// Asc mocks base method.
func (m *MockEngineInterface) Asc(colNames ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range colNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Asc", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Asc indicates an expected call of Asc.
func (mr *MockEngineInterfaceMockRecorder) Asc(colNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Asc", reflect.TypeOf((*MockEngineInterface)(nil).Asc), colNames...)
}

// Before mocks base method.
func (m *MockEngineInterface) Before(arg0 func(any)) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Before", arg0)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Before indicates an expected call of Before.
func (mr *MockEngineInterfaceMockRecorder) Before(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Before", reflect.TypeOf((*MockEngineInterface)(nil).Before), arg0)
}

// BufferSize mocks base method.
func (m *MockEngineInterface) BufferSize(size int) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferSize", size)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// BufferSize indicates an expected call of BufferSize.
func (mr *MockEngineInterfaceMockRecorder) BufferSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferSize", reflect.TypeOf((*MockEngineInterface)(nil).BufferSize), size)
}

// Charset mocks base method.
func (m *MockEngineInterface) Charset(charset string) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charset", charset)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Charset indicates an expected call of Charset.
func (mr *MockEngineInterfaceMockRecorder) Charset(charset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charset", reflect.TypeOf((*MockEngineInterface)(nil).Charset), charset)
}

// ClearCache mocks base method.
func (m *MockEngineInterface) ClearCache(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ClearCache", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCache indicates an expected call of ClearCache.
func (mr *MockEngineInterfaceMockRecorder) ClearCache(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCache", reflect.TypeOf((*MockEngineInterface)(nil).ClearCache), arg0...)
}

// Cols mocks base method.
func (m *MockEngineInterface) Cols(columns ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cols", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Cols indicates an expected call of Cols.
func (mr *MockEngineInterfaceMockRecorder) Cols(columns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cols", reflect.TypeOf((*MockEngineInterface)(nil).Cols), columns...)
}

// Context mocks base method.
func (m *MockEngineInterface) Context(arg0 context.Context) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context", arg0)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEngineInterfaceMockRecorder) Context(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEngineInterface)(nil).Context), arg0)
}

// Count mocks base method.
func (m *MockEngineInterface) Count(arg0 ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockEngineInterfaceMockRecorder) Count(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEngineInterface)(nil).Count), arg0...)
}

// CreateIndexes mocks base method.
func (m *MockEngineInterface) CreateIndexes(bean any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndexes", bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndexes indicates an expected call of CreateIndexes.
func (mr *MockEngineInterfaceMockRecorder) CreateIndexes(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndexes", reflect.TypeOf((*MockEngineInterface)(nil).CreateIndexes), bean)
}

// CreateTables mocks base method.
func (m *MockEngineInterface) CreateTables(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTables", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTables indicates an expected call of CreateTables.
func (mr *MockEngineInterfaceMockRecorder) CreateTables(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTables", reflect.TypeOf((*MockEngineInterface)(nil).CreateTables), arg0...)
}

// CreateUniques mocks base method.
func (m *MockEngineInterface) CreateUniques(bean any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUniques", bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUniques indicates an expected call of CreateUniques.
func (mr *MockEngineInterfaceMockRecorder) CreateUniques(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUniques", reflect.TypeOf((*MockEngineInterface)(nil).CreateUniques), bean)
}

// DBMetas mocks base method.
func (m *MockEngineInterface) DBMetas() ([]*schemas.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBMetas")
	ret0, _ := ret[0].([]*schemas.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DBMetas indicates an expected call of DBMetas.
func (mr *MockEngineInterfaceMockRecorder) DBMetas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBMetas", reflect.TypeOf((*MockEngineInterface)(nil).DBMetas))
}

// DBVersion mocks base method.
func (m *MockEngineInterface) DBVersion() (*schemas.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBVersion")
	ret0, _ := ret[0].(*schemas.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DBVersion indicates an expected call of DBVersion.
func (mr *MockEngineInterfaceMockRecorder) DBVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBVersion", reflect.TypeOf((*MockEngineInterface)(nil).DBVersion))
}

// Decr mocks base method.
func (m *MockEngineInterface) Decr(column string, arg ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{column}
	for _, a := range arg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Decr", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Decr indicates an expected call of Decr.
func (mr *MockEngineInterfaceMockRecorder) Decr(column any, arg ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{column}, arg...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockEngineInterface)(nil).Decr), varargs...)
}

// Delete mocks base method.
func (m *MockEngineInterface) Delete(arg0 ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEngineInterfaceMockRecorder) Delete(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEngineInterface)(nil).Delete), arg0...)
}

// Desc mocks base method.
func (m *MockEngineInterface) Desc(arg0 ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Desc", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Desc indicates an expected call of Desc.
func (mr *MockEngineInterfaceMockRecorder) Desc(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Desc", reflect.TypeOf((*MockEngineInterface)(nil).Desc), arg0...)
}

// Dialect mocks base method.
func (m *MockEngineInterface) Dialect() dialects.Dialect {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dialect")
	ret0, _ := ret[0].(dialects.Dialect)
	return ret0
}

// Dialect indicates an expected call of Dialect.
func (mr *MockEngineInterfaceMockRecorder) Dialect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dialect", reflect.TypeOf((*MockEngineInterface)(nil).Dialect))
}

// Distinct mocks base method.
func (m *MockEngineInterface) Distinct(columns ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Distinct", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Distinct indicates an expected call of Distinct.
func (mr *MockEngineInterfaceMockRecorder) Distinct(columns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distinct", reflect.TypeOf((*MockEngineInterface)(nil).Distinct), columns...)
}

// DriverName mocks base method.
func (m *MockEngineInterface) DriverName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DriverName indicates an expected call of DriverName.
func (mr *MockEngineInterfaceMockRecorder) DriverName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverName", reflect.TypeOf((*MockEngineInterface)(nil).DriverName))
}

// DropIndexes mocks base method.
func (m *MockEngineInterface) DropIndexes(bean any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropIndexes", bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropIndexes indicates an expected call of DropIndexes.
func (mr *MockEngineInterfaceMockRecorder) DropIndexes(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIndexes", reflect.TypeOf((*MockEngineInterface)(nil).DropIndexes), bean)
}

// DropTables mocks base method.
func (m *MockEngineInterface) DropTables(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropTables", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropTables indicates an expected call of DropTables.
func (mr *MockEngineInterfaceMockRecorder) DropTables(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropTables", reflect.TypeOf((*MockEngineInterface)(nil).DropTables), arg0...)
}

// DumpAllToFile mocks base method.
func (m *MockEngineInterface) DumpAllToFile(fp string, tp ...schemas.DBType) error {
	m.ctrl.T.Helper()
	varargs := []any{fp}
	for _, a := range tp {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DumpAllToFile", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DumpAllToFile indicates an expected call of DumpAllToFile.
func (mr *MockEngineInterfaceMockRecorder) DumpAllToFile(fp any, tp ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{fp}, tp...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpAllToFile", reflect.TypeOf((*MockEngineInterface)(nil).DumpAllToFile), varargs...)
}

// EnableSessionID mocks base method.
func (m *MockEngineInterface) EnableSessionID(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableSessionID", arg0)
}

// EnableSessionID indicates an expected call of EnableSessionID.
func (mr *MockEngineInterfaceMockRecorder) EnableSessionID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableSessionID", reflect.TypeOf((*MockEngineInterface)(nil).EnableSessionID), arg0)
}

// Exec mocks base method.
func (m *MockEngineInterface) Exec(sqlOrArgs ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range sqlOrArgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockEngineInterfaceMockRecorder) Exec(sqlOrArgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockEngineInterface)(nil).Exec), sqlOrArgs...)
}

// Exist mocks base method.
func (m *MockEngineInterface) Exist(bean ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range bean {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exist", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exist indicates an expected call of Exist.
func (mr *MockEngineInterfaceMockRecorder) Exist(bean ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exist", reflect.TypeOf((*MockEngineInterface)(nil).Exist), bean...)
}

// Find mocks base method.
func (m *MockEngineInterface) Find(arg0 any, arg1 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Find indicates an expected call of Find.
func (mr *MockEngineInterfaceMockRecorder) Find(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockEngineInterface)(nil).Find), varargs...)
}

// FindAndCount mocks base method.
func (m *MockEngineInterface) FindAndCount(arg0 any, arg1 ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindAndCount", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndCount indicates an expected call of FindAndCount.
func (mr *MockEngineInterfaceMockRecorder) FindAndCount(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndCount", reflect.TypeOf((*MockEngineInterface)(nil).FindAndCount), varargs...)
}

// Get mocks base method.
func (m *MockEngineInterface) Get(arg0 ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEngineInterfaceMockRecorder) Get(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEngineInterface)(nil).Get), arg0...)
}

// GetCacher mocks base method.
func (m *MockEngineInterface) GetCacher(arg0 string) caches.Cacher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacher", arg0)
	ret0, _ := ret[0].(caches.Cacher)
	return ret0
}

// GetCacher indicates an expected call of GetCacher.
func (mr *MockEngineInterfaceMockRecorder) GetCacher(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacher", reflect.TypeOf((*MockEngineInterface)(nil).GetCacher), arg0)
}

// GetColumnMapper mocks base method.
func (m *MockEngineInterface) GetColumnMapper() names.Mapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnMapper")
	ret0, _ := ret[0].(names.Mapper)
	return ret0
}

// GetColumnMapper indicates an expected call of GetColumnMapper.
func (mr *MockEngineInterfaceMockRecorder) GetColumnMapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnMapper", reflect.TypeOf((*MockEngineInterface)(nil).GetColumnMapper))
}

// GetDefaultCacher mocks base method.
func (m *MockEngineInterface) GetDefaultCacher() caches.Cacher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultCacher")
	ret0, _ := ret[0].(caches.Cacher)
	return ret0
}

// GetDefaultCacher indicates an expected call of GetDefaultCacher.
func (mr *MockEngineInterfaceMockRecorder) GetDefaultCacher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultCacher", reflect.TypeOf((*MockEngineInterface)(nil).GetDefaultCacher))
}

// GetTZDatabase mocks base method.
func (m *MockEngineInterface) GetTZDatabase() *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTZDatabase")
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// GetTZDatabase indicates an expected call of GetTZDatabase.
func (mr *MockEngineInterfaceMockRecorder) GetTZDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTZDatabase", reflect.TypeOf((*MockEngineInterface)(nil).GetTZDatabase))
}

// GetTZLocation mocks base method.
func (m *MockEngineInterface) GetTZLocation() *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTZLocation")
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// GetTZLocation indicates an expected call of GetTZLocation.
func (mr *MockEngineInterfaceMockRecorder) GetTZLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTZLocation", reflect.TypeOf((*MockEngineInterface)(nil).GetTZLocation))
}

// GetTableMapper mocks base method.
func (m *MockEngineInterface) GetTableMapper() names.Mapper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableMapper")
	ret0, _ := ret[0].(names.Mapper)
	return ret0
}

// GetTableMapper indicates an expected call of GetTableMapper.
func (mr *MockEngineInterfaceMockRecorder) GetTableMapper() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableMapper", reflect.TypeOf((*MockEngineInterface)(nil).GetTableMapper))
}

// GroupBy mocks base method.
func (m *MockEngineInterface) GroupBy(keys string) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupBy", keys)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// GroupBy indicates an expected call of GroupBy.
func (mr *MockEngineInterfaceMockRecorder) GroupBy(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupBy", reflect.TypeOf((*MockEngineInterface)(nil).GroupBy), keys)
}

// ID mocks base method.
func (m *MockEngineInterface) ID(arg0 any) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID", arg0)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockEngineInterfaceMockRecorder) ID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockEngineInterface)(nil).ID), arg0)
}

// ImportFile mocks base method.
func (m *MockEngineInterface) ImportFile(fp string) ([]sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportFile", fp)
	ret0, _ := ret[0].([]sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportFile indicates an expected call of ImportFile.
func (mr *MockEngineInterfaceMockRecorder) ImportFile(fp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportFile", reflect.TypeOf((*MockEngineInterface)(nil).ImportFile), fp)
}

// In mocks base method.
func (m *MockEngineInterface) In(arg0 string, arg1 ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "In", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// In indicates an expected call of In.
func (mr *MockEngineInterfaceMockRecorder) In(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "In", reflect.TypeOf((*MockEngineInterface)(nil).In), varargs...)
}

// Incr mocks base method.
func (m *MockEngineInterface) Incr(column string, arg ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{column}
	for _, a := range arg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Incr", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Incr indicates an expected call of Incr.
func (mr *MockEngineInterfaceMockRecorder) Incr(column any, arg ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{column}, arg...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockEngineInterface)(nil).Incr), varargs...)
}

// Insert mocks base method.
func (m *MockEngineInterface) Insert(arg0 ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockEngineInterfaceMockRecorder) Insert(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockEngineInterface)(nil).Insert), arg0...)
}

// InsertOne mocks base method.
func (m *MockEngineInterface) InsertOne(arg0 any) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockEngineInterfaceMockRecorder) InsertOne(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockEngineInterface)(nil).InsertOne), arg0)
}

// IsTableEmpty mocks base method.
func (m *MockEngineInterface) IsTableEmpty(bean any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTableEmpty", bean)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTableEmpty indicates an expected call of IsTableEmpty.
func (mr *MockEngineInterfaceMockRecorder) IsTableEmpty(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTableEmpty", reflect.TypeOf((*MockEngineInterface)(nil).IsTableEmpty), bean)
}

// IsTableExist mocks base method.
func (m *MockEngineInterface) IsTableExist(beanOrTableName any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTableExist", beanOrTableName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTableExist indicates an expected call of IsTableExist.
func (mr *MockEngineInterfaceMockRecorder) IsTableExist(beanOrTableName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTableExist", reflect.TypeOf((*MockEngineInterface)(nil).IsTableExist), beanOrTableName)
}

// Iterate mocks base method.
func (m *MockEngineInterface) Iterate(arg0 any, arg1 xorm.IterFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Iterate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Iterate indicates an expected call of Iterate.
func (mr *MockEngineInterfaceMockRecorder) Iterate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iterate", reflect.TypeOf((*MockEngineInterface)(nil).Iterate), arg0, arg1)
}

// Join mocks base method.
func (m *MockEngineInterface) Join(joinOperator string, tablename, condition any, args ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{joinOperator, tablename, condition}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockEngineInterfaceMockRecorder) Join(joinOperator, tablename, condition any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{joinOperator, tablename, condition}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockEngineInterface)(nil).Join), varargs...)
}

// Limit mocks base method.
func (m *MockEngineInterface) Limit(arg0 int, arg1 ...int) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Limit", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockEngineInterfaceMockRecorder) Limit(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockEngineInterface)(nil).Limit), varargs...)
}

// MapCacher mocks base method.
func (m *MockEngineInterface) MapCacher(arg0 any, arg1 caches.Cacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapCacher", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MapCacher indicates an expected call of MapCacher.
func (mr *MockEngineInterfaceMockRecorder) MapCacher(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapCacher", reflect.TypeOf((*MockEngineInterface)(nil).MapCacher), arg0, arg1)
}

// MustCols mocks base method.
func (m *MockEngineInterface) MustCols(columns ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MustCols", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// MustCols indicates an expected call of MustCols.
func (mr *MockEngineInterfaceMockRecorder) MustCols(columns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustCols", reflect.TypeOf((*MockEngineInterface)(nil).MustCols), columns...)
}

// NewSession mocks base method.
func (m *MockEngineInterface) NewSession() *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSession")
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// NewSession indicates an expected call of NewSession.
func (mr *MockEngineInterfaceMockRecorder) NewSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSession", reflect.TypeOf((*MockEngineInterface)(nil).NewSession))
}

// NoAutoCondition mocks base method.
func (m *MockEngineInterface) NoAutoCondition(arg0 ...bool) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NoAutoCondition", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// NoAutoCondition indicates an expected call of NoAutoCondition.
func (mr *MockEngineInterfaceMockRecorder) NoAutoCondition(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoAutoCondition", reflect.TypeOf((*MockEngineInterface)(nil).NoAutoCondition), arg0...)
}

// NoAutoTime mocks base method.
func (m *MockEngineInterface) NoAutoTime() *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoAutoTime")
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// NoAutoTime indicates an expected call of NoAutoTime.
func (mr *MockEngineInterfaceMockRecorder) NoAutoTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoAutoTime", reflect.TypeOf((*MockEngineInterface)(nil).NoAutoTime))
}

// NotIn mocks base method.
func (m *MockEngineInterface) NotIn(arg0 string, arg1 ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NotIn", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// NotIn indicates an expected call of NotIn.
func (mr *MockEngineInterfaceMockRecorder) NotIn(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotIn", reflect.TypeOf((*MockEngineInterface)(nil).NotIn), varargs...)
}

// Nullable mocks base method.
func (m *MockEngineInterface) Nullable(arg0 ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Nullable", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Nullable indicates an expected call of Nullable.
func (mr *MockEngineInterfaceMockRecorder) Nullable(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nullable", reflect.TypeOf((*MockEngineInterface)(nil).Nullable), arg0...)
}

// Omit mocks base method.
func (m *MockEngineInterface) Omit(columns ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range columns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Omit", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Omit indicates an expected call of Omit.
func (mr *MockEngineInterfaceMockRecorder) Omit(columns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Omit", reflect.TypeOf((*MockEngineInterface)(nil).Omit), columns...)
}

// OrderBy mocks base method.
func (m *MockEngineInterface) OrderBy(order any, args ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{order}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OrderBy", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// OrderBy indicates an expected call of OrderBy.
func (mr *MockEngineInterfaceMockRecorder) OrderBy(order any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{order}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBy", reflect.TypeOf((*MockEngineInterface)(nil).OrderBy), varargs...)
}

// Ping mocks base method.
func (m *MockEngineInterface) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEngineInterfaceMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEngineInterface)(nil).Ping))
}

// Prepare mocks base method.
func (m *MockEngineInterface) Prepare() *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare")
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockEngineInterfaceMockRecorder) Prepare() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockEngineInterface)(nil).Prepare))
}

// Query mocks base method.
func (m *MockEngineInterface) Query(sqlOrArgs ...any) ([]map[string][]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range sqlOrArgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockEngineInterfaceMockRecorder) Query(sqlOrArgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockEngineInterface)(nil).Query), sqlOrArgs...)
}

// QueryInterface mocks base method.
func (m *MockEngineInterface) QueryInterface(sqlOrArgs ...any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range sqlOrArgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryInterface", varargs...)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryInterface indicates an expected call of QueryInterface.
func (mr *MockEngineInterfaceMockRecorder) QueryInterface(sqlOrArgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryInterface", reflect.TypeOf((*MockEngineInterface)(nil).QueryInterface), sqlOrArgs...)
}

// QueryString mocks base method.
func (m *MockEngineInterface) QueryString(sqlOrArgs ...any) ([]map[string]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range sqlOrArgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryString", varargs...)
	ret0, _ := ret[0].([]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryString indicates an expected call of QueryString.
func (mr *MockEngineInterfaceMockRecorder) QueryString(sqlOrArgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryString", reflect.TypeOf((*MockEngineInterface)(nil).QueryString), sqlOrArgs...)
}

// Quote mocks base method.
func (m *MockEngineInterface) Quote(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quote", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Quote indicates an expected call of Quote.
func (mr *MockEngineInterfaceMockRecorder) Quote(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quote", reflect.TypeOf((*MockEngineInterface)(nil).Quote), arg0)
}

// Rows mocks base method.
func (m *MockEngineInterface) Rows(bean any) (*xorm.Rows, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rows", bean)
	ret0, _ := ret[0].(*xorm.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rows indicates an expected call of Rows.
func (mr *MockEngineInterfaceMockRecorder) Rows(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rows", reflect.TypeOf((*MockEngineInterface)(nil).Rows), bean)
}

// SQL mocks base method.
func (m *MockEngineInterface) SQL(arg0 any, arg1 ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SQL", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// SQL indicates an expected call of SQL.
func (mr *MockEngineInterfaceMockRecorder) SQL(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SQL", reflect.TypeOf((*MockEngineInterface)(nil).SQL), varargs...)
}

// Select mocks base method.
func (m *MockEngineInterface) Select(arg0 string) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", arg0)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Select indicates an expected call of Select.
func (mr *MockEngineInterfaceMockRecorder) Select(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockEngineInterface)(nil).Select), arg0)
}

// SetCacher mocks base method.
func (m *MockEngineInterface) SetCacher(arg0 string, arg1 caches.Cacher) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCacher", arg0, arg1)
}

// SetCacher indicates an expected call of SetCacher.
func (mr *MockEngineInterfaceMockRecorder) SetCacher(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCacher", reflect.TypeOf((*MockEngineInterface)(nil).SetCacher), arg0, arg1)
}

// SetColumnMapper mocks base method.
func (m *MockEngineInterface) SetColumnMapper(arg0 names.Mapper) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetColumnMapper", arg0)
}

// SetColumnMapper indicates an expected call of SetColumnMapper.
func (mr *MockEngineInterfaceMockRecorder) SetColumnMapper(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetColumnMapper", reflect.TypeOf((*MockEngineInterface)(nil).SetColumnMapper), arg0)
}

// SetConnMaxLifetime mocks base method.
func (m *MockEngineInterface) SetConnMaxLifetime(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConnMaxLifetime", arg0)
}

// SetConnMaxLifetime indicates an expected call of SetConnMaxLifetime.
func (mr *MockEngineInterfaceMockRecorder) SetConnMaxLifetime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnMaxLifetime", reflect.TypeOf((*MockEngineInterface)(nil).SetConnMaxLifetime), arg0)
}

// SetDefaultCacher mocks base method.
func (m *MockEngineInterface) SetDefaultCacher(arg0 caches.Cacher) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefaultCacher", arg0)
}

// SetDefaultCacher indicates an expected call of SetDefaultCacher.
func (mr *MockEngineInterfaceMockRecorder) SetDefaultCacher(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultCacher", reflect.TypeOf((*MockEngineInterface)(nil).SetDefaultCacher), arg0)
}

// SetExpr mocks base method.
func (m *MockEngineInterface) SetExpr(arg0 string, arg1 any) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpr", arg0, arg1)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// SetExpr indicates an expected call of SetExpr.
func (mr *MockEngineInterfaceMockRecorder) SetExpr(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpr", reflect.TypeOf((*MockEngineInterface)(nil).SetExpr), arg0, arg1)
}

// SetLogLevel mocks base method.
func (m *MockEngineInterface) SetLogLevel(arg0 log.LogLevel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogLevel", arg0)
}

// SetLogLevel indicates an expected call of SetLogLevel.
func (mr *MockEngineInterfaceMockRecorder) SetLogLevel(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogLevel", reflect.TypeOf((*MockEngineInterface)(nil).SetLogLevel), arg0)
}

// SetLogger mocks base method.
func (m *MockEngineInterface) SetLogger(logger any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogger", logger)
}

// SetLogger indicates an expected call of SetLogger.
func (mr *MockEngineInterfaceMockRecorder) SetLogger(logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogger", reflect.TypeOf((*MockEngineInterface)(nil).SetLogger), logger)
}

// SetMapper mocks base method.
func (m *MockEngineInterface) SetMapper(arg0 names.Mapper) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMapper", arg0)
}

// SetMapper indicates an expected call of SetMapper.
func (mr *MockEngineInterfaceMockRecorder) SetMapper(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMapper", reflect.TypeOf((*MockEngineInterface)(nil).SetMapper), arg0)
}

// SetMaxIdleConns mocks base method.
func (m *MockEngineInterface) SetMaxIdleConns(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxIdleConns", arg0)
}

// SetMaxIdleConns indicates an expected call of SetMaxIdleConns.
func (mr *MockEngineInterfaceMockRecorder) SetMaxIdleConns(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxIdleConns", reflect.TypeOf((*MockEngineInterface)(nil).SetMaxIdleConns), arg0)
}

// SetMaxOpenConns mocks base method.
func (m *MockEngineInterface) SetMaxOpenConns(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxOpenConns", arg0)
}

// SetMaxOpenConns indicates an expected call of SetMaxOpenConns.
func (mr *MockEngineInterfaceMockRecorder) SetMaxOpenConns(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxOpenConns", reflect.TypeOf((*MockEngineInterface)(nil).SetMaxOpenConns), arg0)
}

// SetQuotePolicy mocks base method.
func (m *MockEngineInterface) SetQuotePolicy(arg0 dialects.QuotePolicy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetQuotePolicy", arg0)
}

// SetQuotePolicy indicates an expected call of SetQuotePolicy.
func (mr *MockEngineInterfaceMockRecorder) SetQuotePolicy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuotePolicy", reflect.TypeOf((*MockEngineInterface)(nil).SetQuotePolicy), arg0)
}

// SetSchema mocks base method.
func (m *MockEngineInterface) SetSchema(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSchema", arg0)
}

// SetSchema indicates an expected call of SetSchema.
func (mr *MockEngineInterfaceMockRecorder) SetSchema(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSchema", reflect.TypeOf((*MockEngineInterface)(nil).SetSchema), arg0)
}

// SetTZDatabase mocks base method.
func (m *MockEngineInterface) SetTZDatabase(tz *time.Location) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTZDatabase", tz)
}

// SetTZDatabase indicates an expected call of SetTZDatabase.
func (mr *MockEngineInterfaceMockRecorder) SetTZDatabase(tz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTZDatabase", reflect.TypeOf((*MockEngineInterface)(nil).SetTZDatabase), tz)
}

// SetTZLocation mocks base method.
func (m *MockEngineInterface) SetTZLocation(tz *time.Location) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTZLocation", tz)
}

// SetTZLocation indicates an expected call of SetTZLocation.
func (mr *MockEngineInterfaceMockRecorder) SetTZLocation(tz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTZLocation", reflect.TypeOf((*MockEngineInterface)(nil).SetTZLocation), tz)
}

// SetTableMapper mocks base method.
func (m *MockEngineInterface) SetTableMapper(arg0 names.Mapper) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTableMapper", arg0)
}

// SetTableMapper indicates an expected call of SetTableMapper.
func (mr *MockEngineInterfaceMockRecorder) SetTableMapper(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTableMapper", reflect.TypeOf((*MockEngineInterface)(nil).SetTableMapper), arg0)
}

// SetTagIdentifier mocks base method.
func (m *MockEngineInterface) SetTagIdentifier(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTagIdentifier", arg0)
}

// SetTagIdentifier indicates an expected call of SetTagIdentifier.
func (mr *MockEngineInterfaceMockRecorder) SetTagIdentifier(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTagIdentifier", reflect.TypeOf((*MockEngineInterface)(nil).SetTagIdentifier), arg0)
}

// ShowSQL mocks base method.
func (m *MockEngineInterface) ShowSQL(show ...bool) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range show {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ShowSQL", varargs...)
}

// ShowSQL indicates an expected call of ShowSQL.
func (mr *MockEngineInterfaceMockRecorder) ShowSQL(show ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSQL", reflect.TypeOf((*MockEngineInterface)(nil).ShowSQL), show...)
}

// StoreEngine mocks base method.
func (m *MockEngineInterface) StoreEngine(storeEngine string) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreEngine", storeEngine)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// StoreEngine indicates an expected call of StoreEngine.
func (mr *MockEngineInterfaceMockRecorder) StoreEngine(storeEngine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreEngine", reflect.TypeOf((*MockEngineInterface)(nil).StoreEngine), storeEngine)
}

// Sum mocks base method.
func (m *MockEngineInterface) Sum(bean any, colName string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", bean, colName)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sum indicates an expected call of Sum.
func (mr *MockEngineInterfaceMockRecorder) Sum(bean, colName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockEngineInterface)(nil).Sum), bean, colName)
}

// SumInt mocks base method.
func (m *MockEngineInterface) SumInt(bean any, colName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumInt", bean, colName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumInt indicates an expected call of SumInt.
func (mr *MockEngineInterfaceMockRecorder) SumInt(bean, colName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumInt", reflect.TypeOf((*MockEngineInterface)(nil).SumInt), bean, colName)
}

// Sums mocks base method.
func (m *MockEngineInterface) Sums(bean any, colNames ...string) ([]float64, error) {
	m.ctrl.T.Helper()
	varargs := []any{bean}
	for _, a := range colNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sums", varargs...)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sums indicates an expected call of Sums.
func (mr *MockEngineInterfaceMockRecorder) Sums(bean any, colNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{bean}, colNames...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sums", reflect.TypeOf((*MockEngineInterface)(nil).Sums), varargs...)
}

// SumsInt mocks base method.
func (m *MockEngineInterface) SumsInt(bean any, colNames ...string) ([]int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{bean}
	for _, a := range colNames {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SumsInt", varargs...)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumsInt indicates an expected call of SumsInt.
func (mr *MockEngineInterfaceMockRecorder) SumsInt(bean any, colNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{bean}, colNames...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumsInt", reflect.TypeOf((*MockEngineInterface)(nil).SumsInt), varargs...)
}

// Sync mocks base method.
func (m *MockEngineInterface) Sync(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockEngineInterfaceMockRecorder) Sync(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockEngineInterface)(nil).Sync), arg0...)
}

// Sync2 mocks base method.
func (m *MockEngineInterface) Sync2(arg0 ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sync2", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync2 indicates an expected call of Sync2.
func (mr *MockEngineInterfaceMockRecorder) Sync2(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync2", reflect.TypeOf((*MockEngineInterface)(nil).Sync2), arg0...)
}

// SyncWithOptions mocks base method.
func (m *MockEngineInterface) SyncWithOptions(arg0 xorm.SyncOptions, arg1 ...any) (*xorm.SyncResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SyncWithOptions", varargs...)
	ret0, _ := ret[0].(*xorm.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncWithOptions indicates an expected call of SyncWithOptions.
func (mr *MockEngineInterfaceMockRecorder) SyncWithOptions(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncWithOptions", reflect.TypeOf((*MockEngineInterface)(nil).SyncWithOptions), varargs...)
}

// Table mocks base method.
func (m *MockEngineInterface) Table(tableNameOrBean any) *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Table", tableNameOrBean)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Table indicates an expected call of Table.
func (mr *MockEngineInterfaceMockRecorder) Table(tableNameOrBean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Table", reflect.TypeOf((*MockEngineInterface)(nil).Table), tableNameOrBean)
}

// TableInfo mocks base method.
func (m *MockEngineInterface) TableInfo(bean any) (*schemas.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TableInfo", bean)
	ret0, _ := ret[0].(*schemas.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TableInfo indicates an expected call of TableInfo.
func (mr *MockEngineInterfaceMockRecorder) TableInfo(bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableInfo", reflect.TypeOf((*MockEngineInterface)(nil).TableInfo), bean)
}

// TableName mocks base method.
func (m *MockEngineInterface) TableName(arg0 any, arg1 ...bool) string {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TableName", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// TableName indicates an expected call of TableName.
func (mr *MockEngineInterfaceMockRecorder) TableName(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TableName", reflect.TypeOf((*MockEngineInterface)(nil).TableName), varargs...)
}

// Truncate mocks base method.
func (m *MockEngineInterface) Truncate(arg0 ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Truncate", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Truncate indicates an expected call of Truncate.
func (mr *MockEngineInterfaceMockRecorder) Truncate(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*MockEngineInterface)(nil).Truncate), arg0...)
}

// UnMapType mocks base method.
func (m *MockEngineInterface) UnMapType(arg0 reflect.Type) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnMapType", arg0)
}

// UnMapType indicates an expected call of UnMapType.
func (mr *MockEngineInterfaceMockRecorder) UnMapType(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnMapType", reflect.TypeOf((*MockEngineInterface)(nil).UnMapType), arg0)
}

// Unscoped mocks base method.
func (m *MockEngineInterface) Unscoped() *xorm.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unscoped")
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Unscoped indicates an expected call of Unscoped.
func (mr *MockEngineInterfaceMockRecorder) Unscoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unscoped", reflect.TypeOf((*MockEngineInterface)(nil).Unscoped))
}

// Update mocks base method.
func (m *MockEngineInterface) Update(bean any, condiBeans ...any) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{bean}
	for _, a := range condiBeans {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEngineInterfaceMockRecorder) Update(bean any, condiBeans ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{bean}, condiBeans...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEngineInterface)(nil).Update), varargs...)
}

// UseBool mocks base method.
func (m *MockEngineInterface) UseBool(arg0 ...string) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UseBool", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// UseBool indicates an expected call of UseBool.
func (mr *MockEngineInterfaceMockRecorder) UseBool(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseBool", reflect.TypeOf((*MockEngineInterface)(nil).UseBool), arg0...)
}

// Where mocks base method.
func (m *MockEngineInterface) Where(arg0 any, arg1 ...any) *xorm.Session {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(*xorm.Session)
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockEngineInterfaceMockRecorder) Where(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockEngineInterface)(nil).Where), varargs...)
}
