// Code generated by MockGen. DO NOT EDIT.
// Source: gorm.io/gorm (interfaces: Dialector)
//
// Generated by this command:
//
//	mockgen -package gorm -destination=./dialector_mock_test.go gorm.io/gorm Dialector
//

// Package gorm is a generated GoMock package.
package gorm

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
	clause "gorm.io/gorm/clause"
	schema "gorm.io/gorm/schema"
)

// MockDialector is a mock of Dialector interface.
type MockDialector struct {
	ctrl     *gomock.Controller
	recorder *MockDialectorMockRecorder
	isgomock struct{}
}

// MockDialectorMockRecorder is the mock recorder for MockDialector.
type MockDialectorMockRecorder struct {
	mock *MockDialector
}

// NewMockDialector creates a new mock instance.
func NewMockDialector(ctrl *gomock.Controller) *MockDialector {
	mock := &MockDialector{ctrl: ctrl}
	mock.recorder = &MockDialectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialector) EXPECT() *MockDialectorMockRecorder {
	return m.recorder
}

// BindVarTo mocks base method.
func (m *MockDialector) BindVarTo(writer clause.Writer, stmt *gorm.Statement, v any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BindVarTo", writer, stmt, v)
}

// BindVarTo indicates an expected call of BindVarTo.
func (mr *MockDialectorMockRecorder) BindVarTo(writer, stmt, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindVarTo", reflect.TypeOf((*MockDialector)(nil).BindVarTo), writer, stmt, v)
}

// DataTypeOf mocks base method.
func (m *MockDialector) DataTypeOf(arg0 *schema.Field) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataTypeOf", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DataTypeOf indicates an expected call of DataTypeOf.
func (mr *MockDialectorMockRecorder) DataTypeOf(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataTypeOf", reflect.TypeOf((*MockDialector)(nil).DataTypeOf), arg0)
}

// DefaultValueOf mocks base method.
func (m *MockDialector) DefaultValueOf(arg0 *schema.Field) clause.Expression {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultValueOf", arg0)
	ret0, _ := ret[0].(clause.Expression)
	return ret0
}

// DefaultValueOf indicates an expected call of DefaultValueOf.
func (mr *MockDialectorMockRecorder) DefaultValueOf(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultValueOf", reflect.TypeOf((*MockDialector)(nil).DefaultValueOf), arg0)
}

// Explain mocks base method.
func (m *MockDialector) Explain(sql string, vars ...any) string {
	m.ctrl.T.Helper()
	varargs := []any{sql}
	for _, a := range vars {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Explain indicates an expected call of Explain.
func (mr *MockDialectorMockRecorder) Explain(sql any, vars ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{sql}, vars...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockDialector)(nil).Explain), varargs...)
}

// Initialize mocks base method.
func (m *MockDialector) Initialize(arg0 *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockDialectorMockRecorder) Initialize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockDialector)(nil).Initialize), arg0)
}

// Migrator mocks base method.
func (m *MockDialector) Migrator(db *gorm.DB) gorm.Migrator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migrator", db)
	ret0, _ := ret[0].(gorm.Migrator)
	return ret0
}

// Migrator indicates an expected call of Migrator.
func (mr *MockDialectorMockRecorder) Migrator(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migrator", reflect.TypeOf((*MockDialector)(nil).Migrator), db)
}

// Name mocks base method.
func (m *MockDialector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDialectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDialector)(nil).Name))
}

// QuoteTo mocks base method.
func (m *MockDialector) QuoteTo(arg0 clause.Writer, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QuoteTo", arg0, arg1)
}

// QuoteTo indicates an expected call of QuoteTo.
func (mr *MockDialectorMockRecorder) QuoteTo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuoteTo", reflect.TypeOf((*MockDialector)(nil).QuoteTo), arg0, arg1)
}
