// Code generated by MockGen. DO NOT EDIT.
// Source: configure.go

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	properties "github.com/magiconair/properties"
)

// MockPropertiesConfigure is a mock of PropertiesConfigure interface.
type MockPropertiesConfigure struct {
	ctrl     *gomock.Controller
	recorder *MockPropertiesConfigureMockRecorder
}

// MockPropertiesConfigureMockRecorder is the mock recorder for MockPropertiesConfigure.
type MockPropertiesConfigureMockRecorder struct {
	mock *MockPropertiesConfigure
}

// NewMockPropertiesConfigure creates a new mock instance.
func NewMockPropertiesConfigure(ctrl *gomock.Controller) *MockPropertiesConfigure {
	mock := &MockPropertiesConfigure{ctrl: ctrl}
	mock.recorder = &MockPropertiesConfigureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertiesConfigure) EXPECT() *MockPropertiesConfigureMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockPropertiesConfigure) Decode(x interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", x)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockPropertiesConfigureMockRecorder) Decode(x interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockPropertiesConfigure)(nil).Decode), x)
}

// FilterStripPrefix mocks base method.
func (m *MockPropertiesConfigure) FilterStripPrefix(prefix string) *properties.Properties {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterStripPrefix", prefix)
	ret0, _ := ret[0].(*properties.Properties)
	return ret0
}

// FilterStripPrefix indicates an expected call of FilterStripPrefix.
func (mr *MockPropertiesConfigureMockRecorder) FilterStripPrefix(prefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterStripPrefix", reflect.TypeOf((*MockPropertiesConfigure)(nil).FilterStripPrefix), prefix)
}

// GetBool mocks base method.
func (m *MockPropertiesConfigure) GetBool(key string, def bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", key, def)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockPropertiesConfigureMockRecorder) GetBool(key, def interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetBool), key, def)
}

// GetFloat64 mocks base method.
func (m *MockPropertiesConfigure) GetFloat64(arg0 string, arg1 float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloat64", arg0, arg1)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetFloat64 indicates an expected call of GetFloat64.
func (mr *MockPropertiesConfigureMockRecorder) GetFloat64(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloat64", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetFloat64), arg0, arg1)
}

// GetInt mocks base method.
func (m *MockPropertiesConfigure) GetInt(key string, def int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", key, def)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInt indicates an expected call of GetInt.
func (mr *MockPropertiesConfigureMockRecorder) GetInt(key, def interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetInt), key, def)
}

// GetInt64 mocks base method.
func (m *MockPropertiesConfigure) GetInt64(arg0 string, arg1 int64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt64", arg0, arg1)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetInt64 indicates an expected call of GetInt64.
func (mr *MockPropertiesConfigureMockRecorder) GetInt64(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt64", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetInt64), arg0, arg1)
}

// GetParsedDuration mocks base method.
func (m *MockPropertiesConfigure) GetParsedDuration(key string, def time.Duration) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParsedDuration", key, def)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetParsedDuration indicates an expected call of GetParsedDuration.
func (mr *MockPropertiesConfigureMockRecorder) GetParsedDuration(key, def interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParsedDuration", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetParsedDuration), key, def)
}

// GetString mocks base method.
func (m *MockPropertiesConfigure) GetString(arg0, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockPropertiesConfigureMockRecorder) GetString(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetString), arg0, arg1)
}

// GetUint mocks base method.
func (m *MockPropertiesConfigure) GetUint(arg0 string, arg1 uint) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUint", arg0, arg1)
	ret0, _ := ret[0].(uint)
	return ret0
}

// GetUint indicates an expected call of GetUint.
func (mr *MockPropertiesConfigureMockRecorder) GetUint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUint", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetUint), arg0, arg1)
}

// GetUint64 mocks base method.
func (m *MockPropertiesConfigure) GetUint64(arg0 string, arg1 uint64) uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUint64", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	return ret0
}

// GetUint64 indicates an expected call of GetUint64.
func (mr *MockPropertiesConfigureMockRecorder) GetUint64(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUint64", reflect.TypeOf((*MockPropertiesConfigure)(nil).GetUint64), arg0, arg1)
}

// Len mocks base method.
func (m *MockPropertiesConfigure) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockPropertiesConfigureMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockPropertiesConfigure)(nil).Len))
}
