name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1.21.x", "1.22.x", "1.23.x", "1.24.x"]
#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
#      - name: Install SQLite
#        run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev
      - name: Gather dependencies
        run: go mod download
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
