### 鉴权失败
GET http://localhost:8080/api/demo/show

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 401, "Response status is not 401");
    });


    client.test("error code is 1000000", function() {
        client.assert(1000000 == response.body.code, "code is error");
    });
%}

### 鉴权成功
GET http://localhost:8080/api/demo/show?auth=pass

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });


    client.test("error code is 1000000", function() {
        client.assert(0 == response.body.code, "code is error");
    });
%}

### 无需鉴权
GET http://localhost:8080/api/demo2/show

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });


    client.test("error code is 1000000", function() {
        client.assert(0 == response.body.code, "code is error");
    });
%}


### 错误
GET http://localhost:8080/api/demo2/error

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });


    client.test("error code is 1000000", function() {
        client.assert(1001000 == response.body.code, "code is error");
    });
%}

### echo api
GET http://localhost:8080/api/demo2/echo?echo=info

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });


    client.test("error code is 1000000", function() {
        client.assert(0 == response.body.code, "code is error");
    });

    client.test("echo data is info", function() {
        client.assert('info' == response.body.data, "code is error");
    });
%}

### inject-query
GET http://localhost:8080/api/inject-query?key=100&key=200

### inject-url-define-param
GET http://localhost:8080/api/inject/100

### inject-http-body json
POST http://localhost:8080/api/inject-http-body
Content-Type: application/json

{
    "echo":"hello"
}

### inject-http-body xml
POST http://localhost:8080/api/inject-http-body
Content-Type: application/xml

<xml>
    <echo>hello</echo>
</xml>

### inject-http-body form-data
POST http://localhost:8080/api/inject-http-body
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="echo"

hello


### inject-http-body x-www-form-urlencoded
POST http://localhost:8080/api/inject-http-body
Content-Type: application/x-www-form-urlencoded

echo=hello

### inject-http-struct
GET http://localhost:8080/api/inject-http-struct
